### ISSUE TITLE
What should be the default setting 

### ISSUE THREAD

**Issue by nileixing** [ogzkc/Binance-Trader#1]
SettingName.TRADING_POOL
SettingName.TRADING_TYPE
SettingName.UNIT_TYPE
SettingName.ORDER_TYPE

**Comment by ogzkc** [comment]
TradingPool -> List of symbols that you will watch and trade, no defaults for this property you can add BTCUSDT for starting
TradingType -> Type name of the Trading algorithm, there are 3 trading types default is -> Defaults.TRADING_TYPE. I recommend ChartFollow
UnitType -> Value or Percentage, decides whether by exact value or percentage for increase-decrease rates. I recommend percentage
OrderType -> Limit or Market, indicates your binance order type. I recommend Market, you can miss your target prices with limit order obviously

Happy trading..

**Comment by nileixing** [comment]
thanks

**Comment by ogzkc** [comment]
You're welcome
